### PR TITLE
Adding 'power' segment for laptop battery level

### PR DESCRIPTION
**Pull request by terabyte**
thought you might like this.  I haven't done any font stuff so you might want to add a battery symbol into it or something?  also, not sure how portable my method for getting powerfull/powernow is, but it works on every laptop I own (N=3) across various versions of debian and ubuntu.  Would def. need to be ported to work on OS X.

### CODE REVIEW

**Comment by terabyte** [comment]
(also, thanks for this awesome theme)

**Comment by terabyte** [comment]
oh man, I just saw https://github.com/bhilburn/powerlevel9k/pull/157, looks way better, gonna go try that now instead. =|

**Comment by terabyte** [comment]
yeah, ok, I'm closing this in favor of 157.  nevermind! =)

**Comment by dritter** [comment]
@terabyte Welcome! The development of this theme is quite hidden in the `next` branch. :wink: Feel  free to try it out.

**Pull request closed without merging**
