### PR TITLE
[Bugfix] white arrow on newline

### PR DESCRIPTION
**Pull request by JulienPivard**
Fix : #977

### CODE REVIEW

**Comment by dritter** [comment]
Sorry for the delay. I merged this as part of `v0.7.0` into our `next` branch.

Thx @JulienPivard

**Comment by bhilburn** [comment]
Thanks so much for the contribution, @JulienPivard! It's very much appreciated `=)`

Since @dritter merged this into `next`, this will be in our next release, v0.7.0! Thanks for participating in P9k, and thanks for the PR!

**Comment by westminsterabi** [comment]
This issue is persisting for me. 

Here are the relevant parts of my config. 

```
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="nerdfont-complete" 
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir newline vcs custom_workspace)
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="teal"
POWERLEVEL9K_CUSTOM_WORKSPACE="echo $WORKSPACE"
POWERLEVEL9K_CUSTOM_WORKSPACE_BACKGROUND="013"
POWERLEVEL9K_CUSTOM_WORKSPACE_FOREGROUND="black"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
```
I tried setting both 
`POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=''`
and 
`POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX_ICON=""`
Neither of those fixed the issue :(

**Comment by JulienPivard** [comment]
@westminsterabi What is your powerlevel9k version ?

**Comment by westminsterabi** [comment]
`head CHANGELOG.md` yields v0.6.7

**Comment by JulienPivard** [comment]
I append this to my configuration :
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX_ICON=''
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=''
```
and all works perfectly.
I can't reproduce your problem

**Comment by romkatv** [comment]
> I append this to my configuration :
> 
> ```
> POWERLEVEL9K_PROMPT_ON_NEWLINE=true
> POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX_ICON=''
> POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=''
> POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON=''
> ```
> 
> and all works perfectly.
> I can't reproduce your problem

These parameters have no meaning in powerlevel9k v0.6.7. I realize that you already know that as you've been around the block long enough to know to avoid this version.

**Comment by JulienPivard** [comment]
Oops my bad, wrong version I'm on next. If y tri the same with that conf : 
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
```
I have no white arrow or any other symbol befor my segment
Capture d’écran 2019-12-22 à 19 52 31

**Comment by romkatv** [comment]
@JulienPivard There are infinitely many configurations for which the unexpected triangle doesn't appear. Perhaps ask the OP in which configuration it *does* appear?

@westminsterabi Just to clear my conscience, note that neither Julien nor myself are using the theme you are using.

**Comment by JulienPivard** [comment]
@westminsterabi can you post your full powerlevel9k configuration  ?

**Pull request closed without merging**
