### PR TITLE
add vpn ip to prompt

### PR DESCRIPTION
**Pull request by golgoth31**
move from master to next branch

### CODE REVIEW

**Comment by shibumi** [comment]
@bhilburn What do you think of this? :)

**Comment by bhilburn** [comment]
@golgoth31 - Nice work! This is a really great PR, and a fantastic first contribution to the project. Welcome to P9k =)

@shibumi @onaforeignshore - Thanks for providing review & feedback in #538!

**Comment by onaforeignshore** [comment]
This prompt is Linux only at the moment and does not support macOS, which does not have `ip`. There is a way to get the info on macOS, as described in #538

**Comment by bhilburn** [comment]
@onaforeignshore - Ah, this needs to be fixed, then, or at the very least tracked. Just opened #540 for this. Thanks!

**Pull request merged**
