### PR TITLE
vpn prompt: change "ip" to "ifconfig" to be used on OSX

### PR DESCRIPTION
**Pull request by golgoth31**
Update of the vpn prompt to use /sbin/ifconfig instead of ip

### CODE REVIEW

**Comment by bhilburn** [comment]
Thanks so much for the PR, @golgoth31! Sorry you went for a few weeks, there, without a response.

We've had a couple of other suggestions for how to handle this in #540 from @onaforeignshore and @guidoilbaldo. Unfortunately, not being a macOS user myself, I have no way of testing these.

If some of our macOS devs could review & test this, and leave comments, that would be fantastic `=)`

**Comment by golgoth31** [comment]
Hi, I found a mac and made some test so, it seems that using ifconfig is working on both Linux and macOS. Of course, If some one knowing macOS well could test and validate it's much better !

**Comment by bhilburn** [comment]
I don't want to let this one bitrot. Are there any other macOS users that wouldn't mind giving this a shot to verify all is well?

**Comment by guidoilbaldo** [comment]
hey, had the chance to test the override in zshrc for other interfaces name (like "tun" for Tunnelblick") as @golgoth31 suggested. It works like a charm, so you can merge this branch :)

**Comment by bhilburn** [comment]
Thanks for the confirmation, @guidoilbaldo! 

@golgoth31 - Great contribution, and thanks for the PR! Welcome to P9k as a contributor `=)`

**Pull request merged**
