### PR TITLE
Icon spaces optimized

### PR DESCRIPTION
**Pull request by dritter**
Just a little optimization of the space around the remote branch icon and the node icon..

### CODE REVIEW

**Comment by bhilburn** [comment]
Do you have a pic of the before and after, by chance?

**Comment by dritter** [comment]
@bhilburn Here we go:

Before:
bildschirmfoto 2015-07-15 um 22 12 31

After:
bildschirmfoto 2015-07-15 um 22 15 31

**Comment by bhilburn** [comment]
Looks awesome! Thanks, @dritter!

**Comment by bhilburn** [comment]
Merged in 1f69d67c2a

**Pull request closed without merging**
