### PR TITLE
add nerd-font support

### PR DESCRIPTION
**Pull request by lcorsini**
This is my proposal to support nerd-font using fontconfig fallback support.
I tested it under linux and iTerm2 on OSX, and seems to work very well, you can see a screen here:
https://github.com/bhilburn/powerlevel9k/issues/382
instead of adding custom codepoints to fontawesome config I create a new config mode and added all nerdfont codepoints (for the complete font variant) there

### CODE REVIEW

**Comment by bhilburn** [comment]
Adding additional font config options is cheap for us, and makes the font for accessible for other users. I'm not a nerdfont user myself, so I need to ask for your help, @lcorsini to make sure we stay up-to-date with the current nerd-font codepoints.

I really appreciate you making this PR and upstreaming this feature, @lcorsini. Nice work =)

**Comment by bhilburn** [comment]
I want to merge this in on `next`, but the changeset is based on `master`. If you get a chance to rebase this branch today, @lcorsini, that would be great. Otherwise I'll get to it tomorrow =)

**Comment by lcorsini** [comment]
Sure I'll try to keep it up to date (maybe implement also the patched version of the font if differs) and improve it as nerd font development continues. As to rebase it, unfortunately I can't do it until monday so I can't help today, I'm sorry

**Comment by SirDoctors** [comment]
@lcorsini What's the status of rebasing what branch your merging on?

**Comment by lcorsini** [comment]
I'll do the rebase this evening, sorry guys got a lot to do at work

**Comment by SirDoctors** [comment]
@bhilburn Looks like its good to merge!

**Comment by bhilburn** [comment]
I just merged #351, which added nerdfont support. I diff'd against this branch to try and get an idea of the changes, but it was impossible for me to really tell as I don't have nerdfonts working on my system. I'm going to open a new issue to discuss this.

**Pull request closed without merging**
