### PR TITLE
Updated few icons to use with git.

### PR DESCRIPTION
**Pull request by tusharsrivastava**
I have updated some icons' utf8 code to look better. Old icons were not matched to many icons.

### CODE REVIEW

**Comment by dritter** [comment]
Thanks for your contribution.

Do you use the "fallback-strategy" of `awesome-terminal-fonts`?
Unfortunately this produces different unicode-codepoints than the "patching-strategy" which this theme is using.. I'll try to suggest a pull request to awesome-terminal-fonts in the next days..

**Comment by bhilburn** [comment]
@tusharsrivastava - Thanks so much for getting involved and submitting a contribution!

@dritter - Are you saying that this PR needs an update to work in a fallback situation?

**Comment by dritter** [comment]
@bhilburn No, I think this PR is meant for the fallback strategy. 

Maybe we should have a new section in the icons-variable to support fallback strategy (`awesome-fallback`). IMHO this should be https://github.com/bhilburn/powerlevel9k/compare/master...tcbbd:master as @tcbbd made a quite complete port.

**Comment by dritter** [comment]
@bhilburn Uhm. Merging this means, that we now have glyphs for fallback- and patching-strategy all together. So Icons are now broken in `awesome-patched`-mode..

It would be better to revert this merge and make a new branch in the `icons`-definition (see my previous comment).

**Comment by bhilburn** [comment]
@dritter - Hm, I'm really having trouble understanding how you would like to handle this, as our icon expert =)

Can you lay out a step-by-step plan for what needs to happen?

**Comment by dritter** [comment]
@bhilburn yes. Now it looks good again on `master` and `next`.

**Comment by bhilburn** [comment]
@dritter - Great! Thanks for confirming!

**Pull request merged**
