### PR TITLE
Added kubectl config's current context

### PR DESCRIPTION
**Pull request by jtaylor32**
I created this little addition locally and thought someone else might enjoy this. It's the current context of your `kubectl` config. Whatever your current is set to it will show in the prompt with the Unicode [Helm](http://www.fileformat.info/info/unicode/char/2388/index.htm) symbol.

Let me know if I need to add anything else or change the function!

### CODE REVIEW

**Comment by jtaylor32** [comment]
Hey @zikes let me know if you see anything you think should change. Thanks!

**Comment by zikes** [comment]
@jtaylor32 Awesome! I made some tweaks and added tests, but Github won't let me PR them to your fork. I did a bunch of Googling and I _think_ this will work:

To have a look at them you can `git remote add zikes https://github.com/zikes/powerlevel9k.git` and `git checkout zikes/kubernetes-context`.  If you want to add them to this PR you can merge mine in with `git checkout origin/kubernetes-context` and `git merge zikes/kubernetes-context`, then push to origin and they'll be included in this PR.

**Comment by jtaylor32** [comment]
@zikes that wasn't working for me. Would it be difficult to clone my repository and add them to the kubernetes-context branch? If that's too tough I might be able to do some funky git stuff. Let me know.

**Comment by zikes** [comment]
I cloned yours, but Github doesn't list you as a fork when I try to PR. I missed a step in my comment: `git pull zikes kubernetes-context`, then you can checkout/merge it.

**Comment by jtaylor32** [comment]
Yeah 😆 exactly. We did the same thing weird you can't branch and PR someone's fork like that.

**Comment by zikes** [comment]
It looks like I forgot to add the new test file to the travis config. Can you add it in `.travis.yaml`?

**Comment by jtaylor32** [comment]
Yeah I can do that. I won't be able to get it in today, but I can get it up tomorrow.

**Comment by bhilburn** [comment]
Nice teamwork, @jtaylor32 & @zikes! I'm excited to get this merged once it's ready =)

**Comment by jtaylor32** [comment]
Just pushed the test changes up should be good to go now @bhilburn! Thanks for all the help @zikes -- it was pretty much all you anyways! :)

**Comment by bhilburn** [comment]
@jtaylor32 - Thanks for the great work, here, and thanks for providing testing and feedback, @zikes! Great work.

I added this to the README and CHANGELOG and merged it into next. Great PR `=)`

**Pull request merged**
