### PR TITLE
Merge engines

### PR DESCRIPTION
**Pull request by onaforeignshore**
# User selectable rendering engine (generator)
This is a total replacement for the master branch.

## General updates
- Both rendering engines are included #471
  - `generators/default` is loaded if `POWERLEVEL9K_GENERATOR="default"` (or not defined)
  - `generators/async` is loaded if `POWERLEVEL9K_GENERATOR="async"` #344
- All segments have been moved into their own files and share the same calling line (`serialize_segment`) meaning one definition for both engines #437
  - developer segments in `segments/develop.zsh`
  - network related segments in `segments/network.zsh`
  - system segments in `segments/system.zsh`
  - integration with todo.sh in `segments/todo.zsh`
  - versioning control systems in `segments/vcs.zsh`
  - virtualization segments in `segments/virtual.zsh`
  - `vi_mode` and `cursor shape` are only loaded when the `async` generator is used: `[[ "${POWERLEVEL9K_GENERATOR}" == "async" ]] && source $script_location/segments/vi_mode.zsh || prompt_vi_mode() {} # not working in default!`
- The main file is now only 142 lines long. This separation makes it easier to get to what you need to changes quicker, since there aren't hundreds of lines of code to search through.

### Detailed updates
- `generators/default` now has a `serialize_segments` wrapper function to enable all segments to be written once for both generators
- `prompt_battery` has support for dynamic icon switching and dynamic background color changing #373 / #468
- `prompt_dir` has been updated with colored separators and bold/color on last directory, as well as configurable home #461
- `vi_mode` has support for changing cursor shape (which cannot be tested at present) #319
- `zshrc-example.zsh` is nearly up to date with all the changes made
- any segment content can be printed in **bold**
- icons in the right prompt can be displayed on the left
- now includes support for zsh-async #504

## TODO
- [ ] `tests` have to be updated for generators and for the following segments:
  - [ ] `default` generator
  - [ ] `async` generator
  - [ ] `async-adv` generator
  - [ ] `prompt_date` returns the date
  - [ ] `prompt_host` returns the local host or SSH #459 / #467
  - [ ] `prompt_user` returns the username or root #459 / #467
  - [ ] `prompt_dir` for icons/background/home #461
- [ ] Merge pull requests
  - [ ] Make python virtualenv configurable. #345
  - [x] update fontconfig icons, using awesome-terminal-fonts maps #385 / #382
  - [ ] Add test for `dir` segment, truncate from right with whitespace in path #425
  - [x] Changing name of nerdfont option per #466 / #458
  - [x] Merging Awesome Font Fix #472
  - [ ] Only show go_version segment if inside GOPATH #473
  - [x] Adds Android icon/battery plugin support #480
- [ ] `segments/*` write function descriptions for missing ones
- [ ] make sure example file is 100% complete
- [ ] see if `vi_mode` can be supported in `default` generator
- [x] see if `vi_mode` can be supported in `async-adv` generator
- [x] add `POWERLEVEL9K_RPROMPT_ICON_LEFT=true` to  `default` generator
- [x] add bold segments to `default` generator
- [x] fix `default` and `async-adv` generators for `_joined` segments

### CODE REVIEW

**Comment by bhilburn** [comment]
Just to lay out a plan for how to handle this branch:

Since this work is all based on @dritter's async work, it's obviously gated by that merge. The `async` change will be the most significant change to P9k since I originally created the project, so it will need to go through a thorough testing & review process. Once that branch is merged, I'll probably shoot to have one release with `async` on its own so that we can get it out into the wild and start fixing bugs. at that point, we'll want to rebase this branch and prep it for merge into `next` to go through it's own primary testing with our developers.

**Comment by onaforeignshore** [comment]
Actually, while this started out using @dritter's work, it is a total rewrite for the advanced async engine. It makes use of Zsh-async instead of using Dominic's work. This also makes it nearly impossible to test using the current methods, as there is late/lazy updating to the prompt after a segment has completed its calculations. This sometimes means having to press a key to get the updated segment. Don't know how we will test for that. Any ideas?

**Comment by ntomsic** [comment]
Is this dead?

**Comment by onaforeignshore** [comment]
It is not dead, just on hiatus at the moment for a few reasons:
1. It is a continuous effort to update the engines when the other ones are updated
2. Since the other ones still use a monolithic file instead of separated files for segments, this complicates matters
3. The master and @dritter 's work use different ways to call the segments. This means when any segments get added to master, they have to be recoded slightly to work with #344 (Async all the segments) and this code base.
4. I am currently busy working on my master's degree, so time is a bit limited at the moment.
Once things have settled down a bit more, I will resume work on this

**Comment by ntomsic** [comment]
A hiatus for almost a year might as well be abandoned :/

**Comment by onaforeignshore** [comment]
Not having worked on this branch for some time, but using it all the time, I will be using and streamlining the code. I will remove the idea of having multiple engines and focus on a single `ZSH-ASYNC` only branch in the near future. I am not giving a timeline, as I will work on this when I have time to, and will attempt to integrate any changes in master into this. I have updated a lot of the code in the next branch and will start with integrating that into the new PR.

I'm going to close this PR for now while I concentrate my efforts on the pure `ZSH-ASYNC` branch, which will allow me to work faster on that since I won't have to keep 3 separate engines up to date.

One major hurdle with this will be the testing of the segments. Since all the code is dependent on asynchronous segment completion, I don't know how that will affect the Travis testing. Will have to look into that issue at a later date once the code is more mature.

**Comment by onaforeignshore** [comment]
I am closing this as this work will be superseded by #771.

**Pull request closed without merging**
