### PR TITLE
Add nerdfont icons

### PR DESCRIPTION
**Pull request by kaymmm**
This doesn't do anything regarding the bigger issues of #97, but it's a short-term fix for people using patched/complete nerd fonts. I added the 'nerd-patched-complete' method to the icons with updated codepoints that reflect the current state of the nerdfonts with relocated octoicons. Maybe until things settle down this can just remain open and people can pull it in as a patch. I haven't tested this extensively, but the few pre-patched nerd fonts whose codepoints I checked against seemed to line up correctly.

### CODE REVIEW

**Comment by bhilburn** [comment]
Thanks, @kaymmm! I actually just commented in #97 regarding @lcorsini's similar changeset.

What are everyone's thoughts on actually just upstreaming this completely, and specing a specific release of nerdfonts? @dritter

**Comment by bhilburn** [comment]
I'm leaning towards we do a full merge, make "nerd-fonts" another supported font configuration, and just peg the version that we are compatible with.

**Comment by bhilburn** [comment]
I just tried to respond by e-mail, but apparently that doesn't work.

Anyway, I noticed you merged `next` and then reverted it, @kaymmm. Did something in `next` break your branch? Last night I changed some code points because it appeared a few had become broken in the `fontawesome` config (e.g., the `OK_ICON` was the [medium.com](medium.com) logo).

**Comment by kaymmm** [comment]
Sorry about that, I was merging using a new mergetool and it left all of the merge info (e.g., >>>>>HEAD) junk from git in there when I pushed. I fixed it and everything looks clean now. As far as I can tell, nothing in `next` was broken, just user error on my end. However, I did change 2 of the icons just now to use nerdfonts instead of emoji (battery and python) since they're not displaying correctly on my linux box. The AWS elastic beanstalk icon is broken for me too, but I couldn't find a suitable replacement and just left it as-is.

Let me know if there is anything else you'd like added/changed for this to land in `next`.

**Comment by kaymmm** [comment]
dang. nevermind, I screwed up my merge worse than I thought. It is missing the latest commits you made yesterday and thinks that it already merged origin. Let me see if I can fix it with a rebase in my repo.

**Comment by dritter** [comment]
Oops. I forgot to look into this PR. Sorry @kaymmm 

I am good to go with supporting nerd-fonts officially. But we should make clear in the README that we support the complete version only. That could confuse people.

**Comment by bhilburn** [comment]
This branch is now merged into `next`, with the name changed to `nerdfont-fontconfig`.

**Pull request merged**
