### PR TITLE
Home/folder icon fix

### PR DESCRIPTION
**Pull request by dritter**
This is a PR for #158 . Now if you are beneath the home directory, you'll get a home icon. If you are somewhere else, you'll get a folder icon.

### CODE REVIEW

**Comment by Tritlo** [comment]
Nice! Looks good to me!

**Comment by dritter** [comment]
@Tritlo Could you do me a favor? I see you use the `awesome-fontconfig` mode. Could you give me the code point for the folder icon: 
bildschirmfoto 2015-11-28 um 00 31 07


Thank you very much!

**Comment by Tritlo** [comment]
The closest that I see are

      : f115  and  : f116 

and 
    
      : f07c   : f07d

**Comment by dritter** [comment]
Now it works correctly. ;) The truncation made it a bit harder, so we had to evaluate the path always by our own.

**Pull request merged**
