### PR TITLE
Add elapse time

### PR DESCRIPTION
**Pull request by faizhasim**

### CODE REVIEW

**Comment by dritter** [comment]
Don't you want to share that feature with us all? :wink:

**Comment by faizhasim** [comment]
Happy to. But I couldn't get it working yet.

**Comment by bhilburn** [comment]
Bummer. Can you give us a bit more information about what you were trying to achieve? Perhaps we can get it working together.

**Comment by dritter** [comment]
@faizhasim Maybe this link helps you: https://coderwall.com/p/kmchbw/zsh-display-commands-runtime-in-prompt

**Pull request closed without merging**
