### PR TITLE
missing icons in nerdfont-fontconfig

### PR DESCRIPTION
**Pull request by lcorsini**
Ok here is my pull request, I merged your existing glyphs and added the ones that where missing
see screenshot
pr

### CODE REVIEW

**Comment by dritter** [comment]
@lcorsini Thanks for the PR! One request: @nate0001 found in #448 some other icons (the extended `VCS_GIT_*`) to be missing. Could you add them as well?
[Here](https://github.com/bhilburn/powerlevel9k/blob/ec50da4ac5c34046fea46d1e9eb0bebbfd21d01d/functions/vcs.zsh#L114-L122) are the icon names.

That would be awesome. Thanks in advance!

**Comment by lcorsini** [comment]
sure, I'll give it a look

**Comment by lcorsini** [comment]
I've added them, if there is something still missing tell me

**Comment by dritter** [comment]
According to my tests in #446 , the following icons are missing in `nerdfont-fontconfig` mode:
bildschirmfoto 2017-03-20 um 08 17 57

In `awesome-patched` mode they look like this:
bildschirmfoto 2017-03-20 um 08 21 45

And could you replace the old nerdfont-fontconfig icons array? That would make it easier to compare and merge ;)

**Comment by lcorsini** [comment]
No problem to add them, but I have some problem with this 
`build_left_prompt:11: command not found: prompt_ssh ` 

`And could you replace the old nerdfont-fontconfig icons array? That would make it easier to compare and merge ;)`
What you mean by replace tho old nerdfont-fontconfig?

**Comment by dritter** [comment]
Thanks @lcorsini !

Hmm. May it be that you use our own fork as checkout? [Your next](https://github.com/lcorsini/powerlevel9k/blob/next/powerlevel9k.zsh-theme) seems a bit outdated, and does not have `prompt_ssh`...

> What you mean by replace tho old nerdfont-fontconfig?

If you look at the [diff](https://github.com/bhilburn/powerlevel9k/pull/439/files) of your PR, there are only additions, no deletions. This means that you added a completely new icons array and did not replace the icons in the existing one.

**Comment by lcorsini** [comment]
Ok, I'll check this out, maybe I did something wrong when forked the repo

**Comment by lcorsini** [comment]
Ok, I think I got everything in place now, the new PR is https://github.com/bhilburn/powerlevel9k/pull/451
you can close this one

**Comment by dritter** [comment]
Closed in favour of #451

**Pull request closed without merging**
