### PR TITLE
Add test for `dir` segment, truncate from right with whitespace in path

### PR DESCRIPTION
**Pull request by dritter**
Do not merge! This is not ready yet! This is an attempt to reproduce #308 .
I need to create a PR to execute the tests on travis (although they were green on my local machine).

### CODE REVIEW

**Comment by bhilburn** [comment]
Still not merging =)

**Comment by bhilburn** [comment]
Just confirming that I still have not merged this! ;)

**Comment by bhilburn** [comment]
@dritter - Is this worth keeping open or should we close?

**Comment by dritter** [comment]
Ah. I forgot about this one.. Yep. Closing.

**Pull request closed without merging**
