### PR TITLE
Allow showing the number of jobs even if there is <= 1 job present.

### PR DESCRIPTION
**Pull request by ParthKolekar**
Allow showing the number of jobs even if there is <= 1 job present.

Solves #561 better.

### CODE REVIEW

**Comment by ParthKolekar** [comment]
@bhilburn 

This is a tiny aesthetic commit that does not change default behaviour, can this be merged?

**Comment by bhilburn** [comment]
@ParthKolekar - Thanks so much for submitting this PR! I made some minor changes, including cleaning up some language, and changed the variable name from `_EVEN_ONE` to `_ALWAYS` to be more consistent with our other fields. Note that I am merging this into `next`, instead of `master`, as it's technically a new feature and we try to keep `master` clear of anything except bug fixes between releases. 

Thanks for putting this together! I especially appreciate you updating the docs, as well. Pull & switch over to the next branch to use your code in mainline, and welcome to P9k! `=)`

**Comment by ParthKolekar** [comment]
I actually use prezto... So I guess I need to search for how to set a git submodule to this branch.... 😅 

Thanks for merging.

**Comment by bhilburn** [comment]
@ParthKolekar - git submodules are actually exactly like normal git repos, except their "HEADS" are usually detached... I'm not a prezto user myself, but you should be able to just `cd` into the directory and do a `git checkout -b next -t origin/next` and be good, hah :)

**Pull request merged**
