### PR TITLE
Battery segment fix and enhancement.

### PR DESCRIPTION
**Pull request by Tritlo**
This closes issue #151, and also makes the coloring make more sense. Now the color of the text follows the color of the icon, i.e. red text for low battery, yellow for charging, etc.

### CODE REVIEW

**Comment by Tritlo** [comment]
is %f not stacked, i.e. if I do 

    %F{blue}%F{green}%f

will the color not be blue still? I'm worried that we won't have equal numbers of %f and %F

**Comment by rjorgenson** [comment]
I don't believe you need a %f for every %F, in it's current state it has two foreground color declarations(one for the battery icon, one for the time remaining string) and only one %f at the end to reset it. When using your example above, the output after %F{blue} but before %F{green} will be blue, anything after %F{green} and before %f will be green, anything after %f will be the default color of the terminal. Basically %F means "start printing this color until I say otherwise" and %f means "stop printing any color"

**Comment by Tritlo** [comment]
Alright, then your version makes more sense.

**Comment by rjorgenson** [comment]
Also I had $conn only be set in the instance of a color being applied to the icon so that it would inherit the specified foreground color instead of using the default. We can add a new line to explicitly set it to the foreground color at the top like the others and remove line 258

```
[[ -z $POWERLEVEL9K_BATTERY_FOREGROUND ]] && local conn="$DEFAULT_COLOR" || local conn=$POWERLEVEL9K_BATTERY_FOREGROUND
```

The general thinking behind the way I did it was that unless explicitly set in an option, color should only be there when it's indicating something, and should be as minimal as possible since it's supposed to stand out.

**Comment by rjorgenson** [comment]
I guess with the new changes we'd want to set conn to DEFAULT_COLOR_INVERTED instead, otherwise it will just be set to the same as the background color by default.

**Comment by Tritlo** [comment]
alright, that's been fixed, and the commits squashed together.

**Comment by rjorgenson** [comment]
It still shows just explicitly setting conn to the default color, could you add the line from above that allows it to be the foreground color by default if one is specified.

**Comment by Tritlo** [comment]
You want to overwrite the color of the icon as well?

**Comment by rjorgenson** [comment]
The way it's written, $conn takes precedence over the foreground color, but if there's no condition to set $conn(it's only set when fully charged, charging or low), it should display the icon with the foreground color. The way it is right now it will display the icon with the default inverted color regardless of any user settings when it's in it's normal operating range and not being charged. $conn was intentionally left empty before if not explicitly set to inherit the foreground color, whatever it happened to be set to. If we want it explicitly set to something it should still maintain the same functionality.

**Comment by Tritlo** [comment]
Ok, now it defaults to the foreground color.

**Comment by rjorgenson** [comment]
Thanks =]

**Comment by bhilburn** [comment]
Great PR, @Tritlo! And thanks for providing input, @rjorgenson!

**Pull request merged**
