### PR TITLE
new prompt_date; updated prompt_time

### PR DESCRIPTION
**Pull request by onaforeignshore**
Added new prompt_date segment with an icon
Added ability to set a time icon

### CODE REVIEW

**Comment by bhilburn** [comment]
Thanks for another great PR, @onaforeignshore!

One issue I see is that we currently have neither a `DATE_ICON` nor a `TIME_ICON`. Can you update your PR to add these to the icons settings?

**Comment by onaforeignshore** [comment]
Is there a specific order for the icons declared in `icons.zsh`? Can we make them alphabetical?

**Comment by bhilburn** [comment]
@onaforeignshore - Great point. This isn't consistent at all.

Let's go ahead and fix that in this PR. I like the idea of making them alphabetical =)

**Comment by bhilburn** [comment]
Are you still planning on finishing this one up, @onaforeignshore? It's a good PR, and I don't want to lose it =)

**Comment by onaforeignshore** [comment]
Anything else needed before merge?

**Comment by bhilburn** [comment]
@onaforeignshore - This branch currently has conflicts, and so is unmergeable in its current form. It also looks like it may have been based on an older version of `master`, perhaps? It was missing a number of icons that were merged a while ago, including `Android` and `Windows`.

I've pushed your branch, plus some fixes I've made, to a new branch, and opened #533 to get it merged =)

**Pull request closed without merging**
