### PR TITLE
[Bugfix] Attempt to fix broken ctrl-c behavior

### PR DESCRIPTION
**Pull request by Syphdias**
#### Description
This PR tries to fix the bug mentioned in #812 and #1027. If you hold `crtl-c` the prompt build stops before evaluating the functions in `$PROMPT` and leaves the raw strings behind.
I approach this by evaluating the functions inside `$PROMPT`, i.e. `__p9k_build_left_prompt`, in function `__p9k_prepare_prompt` and writing it to a newly introduced global variable `$__p9k_unsafe_PROMPT` (this is probably against the style guide since I wrote part of the varibale in capital letters. I will change it if requested, of course).  
The unsafe variable is then put into `$PROMPT` with _single_ quotes: `PROMPT='$__p9k_unsafe_PROMPT'`. This is done to prevent evil code to be executed if the contents of the unsafe variable is tainted after evaluating __p9k_build_left_prompt. The same is done for `$RPROMPT`

The benefit is, that since the function `__p9k_prepare_promt` is run as a precmd hook, it can be interrupted without leaving `$PROMPT` unchanged/raw. This also means it could be out of date, but this is still better than no prompt.

#### Question/Problem
Currently I'm having trouble running tests since I get lots of errors regarding background_jobs on stderr. Example:
```zsh
function setUp() {
  export TERM="xterm-256color"
  source powerlevel9k.zsh-theme
}
function testFoo() {
  cd /
}
source shunit2/shunit2
```
Running this test yields
```
 ❱ zsh foo.spec                             
testFoo
prompt_background_jobs:2: bad math expression: operand expected at end of string

Ran 1 test.

OK
```
I think this is the important part (run with `set -xv` right before the `cd /`)
```zsh
+__p9k_build_right_prompt:19> index=3 
+__p9k_build_right_prompt:4> element=background_jobs
+__p9k_build_right_prompt:6> [[ nd_jobs == _joined ]]
+__p9k_build_right_prompt:6> joined=false 
+__p9k_build_right_prompt:9> element=background_jobs 
+__p9k_build_right_prompt:13> [[ $element[0,7] -regex-match "custom_" ]]
+__p9k_build_right_prompt:16> prompt_background_jobs right 3 false
+prompt_background_jobs:1> local jobs_print=''
prompt_background_jobs:2: bad math expression: operand expected at end of string
+__p9k_prepare_prompts:40> __p9k_unsafe_RPROMPT=$'%f%b%k%F{000}%K{000}%F{002} %F{002}✔ %{\C-[[00m%}' 
+__p9k_prepare_prompts:41> RPROMPT='$__p9k_unsafe_RPROMPT' 
+__p9k_prepare_prompts:46> [[ '' == Yes ]]
+__p9k_prepare_prompts:49> local NEWLINE=$'\n'
+__p9k_prepare_prompts:52> [[ false == true ]]
+__p9k_prepare_prompts:63> PROMPT='$__p9k_unsafe_PROMPT' 
+__p9k_ch_pwd:2> __p9k_preexec
+__p9k_preexec:6> _P9K_TIMER_START=1544831671.7253572941 
+testFoo:3> set +vx
```
The problem seems to be the following (backwards):
- `prompt_background_jobs` line 2: `local total_jobs=$((  +  ))` because `$jobs_running` and `$jobs_suspended` are not set
- should be set in `__p9k_background_jobs` trigged by another precmd executed before (as far as I'm aware) `__p9k_prepare_prompt`
- this function never runs and I don't understand why since `add-zsh-hook -L` outputs this:
```zsh
 ❱ cat /tmp/hooks
typeset -g -a preexec_functions=( __p9k_preexec )
typeset -g -a chpwd_functions=( __p9k_ch_pwd )
typeset -g -a precmd_functions=( __p9k_background_jobs __p9k_prepare_prompts )
```

I have an idea for a workaround to change `segments/background_jobs.p9k#L42` to:
```zsh
  local total_jobs=$(( ${jobs_running:-0} + ${jobs_suspended:-0} ))
```

But it worked before, so maybe I'm missing something obvious why one precmd hook is not running.

### CODE REVIEW

**Comment by Syphdias** [comment]
What I use for debugging:
```zsh
 ❱ cat foo.spec NC
setopt shwordsplit
SHUNIT_PARENT=$0
function setUp() {
  export TERM="xterm-256color"
  source powerlevel9k.zsh-theme
}
function testLeftMultilinePrompt() {
  local -a P9K_LEFT_PROMPT_ELEMENTS
  P9K_LEFT_PROMPT_ELEMENTS=(custom_world1)
  local P9K_CUSTOM_WORLD1='echo world1'
  local P9K_PROMPT_ON_NEWLINE=true
  __p9k_prepare_prompts
  local nl=$'\n'
  assertEquals "╭─%f%b%k%K{015} %F{000}world1 %k%F{015}%f ${nl}╰─ " "${(e)PROMPT}"
}
source shunit2/shunit2
```
On `fix-ctrl-c`:
```
 ❱ ./foo.spec                       
testLeftMultilinePrompt
prompt_background_jobs:2: bad math expression: operand expected at end of string

Ran 1 test.

OK
```
On `next`:
```
 ❱ ./foo.spec          
testLeftMultilinePrompt

Ran 1 test.

OK
```
So, I think it comes down to `__p9k_background_jobs` and `__p9k_prepare_prompts`. On `fix-ctrl-c`:
  * If I remove `__p9k_prepare_prompts` the error is gone but the `assetEqual` fails
  * If I add `__p9k_background_jobs` before `__p9k_prepare_prompts` the test succeeds and the error is gone -> I'm not satisfied with this solution since the test has nothing to do with `background_jobs` and presumably comes from the default `$RPROMPT`. A potential solution could be to remove every irrelevant segments for each test  in `setUp` for all tests (or in `oneTimeSetUp`).
  * If I execute `__p9k_background_jobs` in a previous test (see below) even if it does nothing. The test succeeds and the error is gone. So there seems to be some kind of shared environment.
```zsh
function testNothing() {
  __p9k_background_jobs
}
```
  * Funnily the test for the segment `background_jobs` does not depend on `__p9k_background_jobs` since it sets the variables manually. This basically means this function is never tested, doesn't it?

I don't understand why this is not happening on `next` but not on `fix-ctrl-c`. I'd appreciate any ideas and potential ways to fix this. What's even broken? The code or the tests?

**Comment by Syphdias** [comment]
OK, writing about this issue really helped. The problem is that on `next` with the simple `__p9k_build_left_prompt` the right prompt was simply ignored with a unevaluated `$(__p9k_build_right_prompt)`. This changed when I moved the evaluation to `__p9k_prepare_prompts`.

My solution would be to include this in every `setUp` that does not rely on the right prompt:
```
local -a P9K_RIGHT_PROMPT_ELEMENTS
P9K_RIGHT_PROMPT_ELEMENTS=()
```
Can someone comment on if this is a good way to fix this or if it should be done differently?

**Comment by Syphdias** [comment]
On test is missing a fix:
`ssertEquals '╭─[39m[0m[49m[107m [30mworld [49m[97m[39m  ╰─ [1A[39m[0m[49m[97m[107m[30m rworld [30m [00m[1B' "$(print -P ${PROMPT}${RPROMPT})"`
What it should be (left):
```
00000000: e295 ade2 9480 1b5b 3339 6d1b 5b30 6d1b  .......[39m.[0m.
00000010: 5b34 396d 1b5b 3130 376d 201b 5b33 306d  [49m.[107m .[30m
00000020: 776f 726c 6420 1b5b 3439 6d1b 5b39 376d  world .[49m.[97m
00000030: ee82 b01b 5b33 396d 2020 e295 b0e2 9480  ....[39m  ......
00000040: 201b 5b31 411b 5b33 396d 1b5b 306d 1b5b   .[1A.[39m.[0m.[
00000050: 3439 6d1b 5b39 376d ee82 b21b 5b31 3037  49m.[97m....[107
00000060: 6d1b 5b33 306d 2072 776f 726c 6420 1b5b  m.[30m rworld .[
00000070: 3330 6d20 1b5b 3030 6d1b 5b31 420a       30m .[00m.[1B.
```
What it is (right):
```
00000000: e295 ade2 9480 1b5b 3339 6d1b 5b30 6d1b  .......[39m.[0m.
00000010: 5b34 396d 1b5b 3130 376d 201b 5b33 306d  [49m.[107m .[30m
00000020: 776f 726c 6420 1b5b 3439 6d1b 5b39 376d  world .[49m.[97m
00000030: ee82 b01b 5b33 396d 200a e295 b0e2 9480  ....[39m .......
00000040: 201b 5b31 411b 5b33 396d 1b5b 306d 1b5b   .[1A.[39m.[0m.[
00000050: 3439 6d1b 5b39 376d ee82 b21b 5b31 3037  49m.[97m....[107
00000060: 6d1b 5b33 306d 2072 776f 726c 6420 1b5b  m.[30m rworld .[
00000070: 3330 6d20 1b5b 3030 6d1b 5b31 420a       30m .[00m.[1B.
```

Not sure why a space is being turned into a linefeed...
```
diff 1 2
4c4
< 00000030: ee82 b01b 5b33 396d 2020 e295 b0e2 9480  ....[39m  ......
---
> 00000030: ee82 b01b 5b33 396d 200a e295 b0e2 9480  ....[39m .......
```

**Comment by dritter** [comment]
Yeah. That test is really fragile. But I wanted to have a kind of integration test. The trade-off is a lot of non-printable characters (like for cursor movement). 🙄 
Not sure, why that character changed. I always suspect the editor I am using for changing that..

**Comment by Syphdias** [comment]
Sadly, it's not the editor. There is no diff to previous commits

**Comment by Syphdias** [comment]
Rebased to next and tried the debugging comments:
image

I guess [this linebreak](https://github.com/bhilburn/powerlevel9k/pull/1119/files#diff-1f035442adbeec17a57209c772b7adc1L390) is the reason. But why is it not there in the "old" version. That is what confuses me. The linefeed was converted into a space. But there should have always been a linebreak, shouldn't it?

**Comment by Syphdias** [comment]
I modified the test (91e7b62691e75051991af44e0d131baf22f10ff9) to see if all checks go green after that. This is quite unsatisfying, though. Please give this a thorough look if this is a valid change, @dritter, @bhilburn!
Also, @dritter suggested to add `autoload -Uz zsh/parameter` in cdbd0621a02a3d2c7727e39f0962a4081855c675. I couldn't see any difference. Should I cherry-pick it anyway?

**Comment by dritter** [comment]
I think the newline was there before as well, but not visible. If I debug the code (current `master`; 2f4b15041fe31d85dc9ef705b818c3a0e6985da3 ), I see the newline:
```zsh
+powerlevel9k_prepare_prompts:17> PROMPT=$'$(print_icon MULTILINE_FIRST_PROMPT_PREFIX)%f%b%k$(build_left_prompt)\n$(print_icon MULTILINE_LAST_PROMPT_PREFIX)'
```

Your codebase ( 91e7b62691e75051991af44e0d131baf22f10ff9 ) looks in the debugger like this:
```zsh
__p9k_unsafe_PROMPT=$'╭─%f%b%k%K{015} %F{000}world %k%F{015}%f \n╰─ '
```
So the newline is there in both versions, only you needed to make that newline explicit in the test. Btw. there is another glitch. The contents of `__p9k_unsafe_PROMPT` seems cut off, which is IMHO because we mess around with the cursor.

So for me I am alright with that change..

Btw. my commit was for the background jobs to work properly, but this is set by default.. Would make the code a tiny bit more explicit.

**Comment by Syphdias** [comment]
rebase to current `next` contains:
* not changing shunit (was an accident)
* changing sourcing from `segment/{segment}.p9k` to `segment/${segment}/${segment}.p9k`
* correcting typo in commit message

**Comment by Syphdias** [comment]
p9k_flowchart probably needs some slight adjustments now...

**Comment by dritter** [comment]
I updated the flowchart. @Syphdias @onaforeignshore Could you review it. Will merge afterwards.

**Comment by Syphdias** [comment]
Failed tests seem to be arbitrary. Maybe a brew problem. Can someone retrigger them?

**Comment by dritter** [comment]
Tests triggered @Syphdias

**Comment by dritter** [comment]
Thx @Syphdias .

**Pull request merged**
