### PR TITLE
Split up `ram` segment into `ram` and `swap`.

### PR DESCRIPTION
**Pull request by dritter**
This is more flexible, and we save a variable.

If users wish to have this as one segment, the can join them together..

### CODE REVIEW

**Comment by bhilburn** [comment]
@dritter - Looks like we've got some merge conflicts on this one. Can you update?

**Comment by dritter** [comment]
I think this is an issue for 0.4.0. I'll update this PR once 0.3.1 is out.

**Comment by bhilburn** [comment]
@dritter - Roger.

**Comment by bhilburn** [comment]
@dritter - Thanks for updating this! Looks ready `=)`

**Pull request merged**
