### PR TITLE
Even less dependencies

### PR DESCRIPTION
**Pull request by dritter**
If `sed q | wc -l` is just for testing if the string is empty or not, we can do that with just ZSH. Trusting that the implentation of `test -n` is intelligent enough to abort if a character is found. Even that `sed q` might be super fast, the big amount of indirections seem quite slow to me.

This is an addition to #60 

I tested this with OSX and the vagrant-ubuntu.

### CODE REVIEW

**Comment by bhilburn** [comment]
This does appear to do the trick, and I like the cleaner code! Thanks, @dritter!

**Comment by dritter** [comment]
Only thing is that if the `git` command returns an empty string as first line this might fail.. But it think this is an edge case we could ignore. If anyone has issues with this solution, we still could switch back. But IMHO this is not going to happen..

**Comment by bhilburn** [comment]
@dritter - Tracking whether or not something causes a breakage for people is really hard to track, and might frustrate people to the point that they stop using the theme. I would rather make sure that this won't break anything for people, and then migrate to it knowing that it's stable.

Towards that, I'm staging it into an `unstable` branch. More, shortly `=)`

**Comment by bhilburn** [comment]
This work has been merged into `next` for testing.

https://github.com/bhilburn/powerlevel9k/tree/next

**Pull request closed without merging**
