### PR TITLE
Fix MacOS specific battery segment logic.

### PR DESCRIPTION
**Pull request by jshort**
The case statement was causing it to never display that it was charging
and some of the awk statements had an off-by-one bug to grab the correct
values.

### CODE REVIEW

**Comment by jshort** [comment]
Hmm @rjorgenson, looking at https://cloud.githubusercontent.com/assets/44096/21557670/10a0e2dc-cded-11e6-84a8-157c8efd89a3.png

I see that your `pmset -g batt` output is subtly different than mine (wrt to the id=xxxxxxx part) so I think the simple `awk` parsing isn't going to be sufficient.

**Comment by jshort** [comment]
Ok check out the last commit.  I changed it to split on `;` first and then on whitespace if need be.  This will work on `pmset -g batt` output both like mine:

 ```
❯  pmset -g batt                                                                              
Now drawing from 'AC Power'
 -InternalBattery-0 	43%; charging; 2:13 remaining present: true
```

And if (id=xxxxxxxx) is in the `pmset` output like on @rjorgenson's machine.

**Comment by rjorgenson** [comment]
@jshort tested your most recent commit and I didn't run into any problems on my end with the extra id column on pmset. Good catch and great job on the fix! =]

@bhilburn This should probably be merged into next before release because it appears the initial migration to pmset that I did doesn't work on some older versions of OS X, I was only able to test on Sierra but it breaks on El Capitan and presumably versions before that as well.

**Comment by bhilburn** [comment]
@rjorgenson - Thanks for the review & recommendation! Much appreciated.

@jshort - Fantastic contribution! Thanks for getting involved. Happy to have this merged =)

**Pull request merged**
