### PR TITLE
Add prompt for current installed swift version

### PR DESCRIPTION
**Pull request by thomaspaulmann**
This commit will add a prompt for the current installed swift version. As soon as the PR is merged, I will add a configuration example to the [Wiki](https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config).

screen shot 2016-12-02 at 09 21 54

### CODE REVIEW

**Comment by dritter** [comment]
@thomaspaulmann Nice work! Thanks for the contribution @thomaspaulmann 
Could you do us a favor and rebase the PR against `next` as this is our dev branch. Thanks.

**Comment by thomaspaulmann** [comment]
@dritter Done!

**Comment by thomaspaulmann** [comment]
@dritter Am I assume correctly that the changes will be available with release v0.6.0? That depends mostly on #344,right?

**Comment by dritter** [comment]
@thomaspaulmann Yep. I am sure @bhilburn will merge this soon in next. ;)

**Comment by bhilburn** [comment]
Thanks for the great new segment, @thomaspaulmann! This will be in the `v0.6.0` master release! `=)`

**Comment by thomaspaulmann** [comment]
@dritter @bhilburn Thanks for being part of Powerlevel, awesome theme!

**Comment by thomaspaulmann** [comment]
I will add my custom configuration as soon as `v0.6.0` was released.

**Pull request merged**
