### PR TITLE
Rewrite - Test branch in progress

### PR DESCRIPTION
**Pull request by onaforeignshore**
After the various discussions about streamlining and speeding up powerlevel9k - especially with precompiling as much as possible and removing tests wherever possible, I have updated the entire code base (based on #771).

This is a WIP as it does not now have a rewritten zsh-async.p9k yet, but it seems to be a whole lot faster.

@bhilburn @dritter Please give it a try and let me know what you think.

### CODE REVIEW

**Comment by onaforeignshore** [comment]
I haven't updated any of the tests, as I want to know what your comments are first before I continue with the work.

**Comment by onaforeignshore** [comment]
#817 - Something like this?

**Comment by bhilburn** [comment]
@onaforeignshore - Holy crap! This is a _ton_ of work. Right off the bat, I can tell you I'm seeing a significant improvement in performance relative to the current HEAD of `next`, but it appears to actually be slower compared to the work in #771 on my machine:

current HEAD of `next`:
screen shot 2018-05-23 at 09 27 48

current HEAD of this dev branch:
screen shot 2018-05-23 at 09 27 54

553c788e8382 from #771:
screen shot 2018-05-23 at 09 30 56

You can also see there are some minor hiccups with colors and icons, but I realize this is all WIP.

So, just to make sure I understand, this branch is built on top of #771, and is basically meant to apply the discussion from #817 regarding Speed vs Flexibility to the code base, right?

I haven't reviewed the code as thoroughly as @dritter has, but everything I've looked at so far is much better organized and easier to understand.

@onaforeignshore - What kinds of performance numbers are you getting on this branch relative to #771? I wonder if something is just wonky with my configuration / machine.

**Comment by onaforeignshore** [comment]
@bhilburn – These are my response times:

Rewrite:
[cid:image001.png@01D3F2C2.8877DBD0]

Code Separation:
[cid:image002.png@01D3F2C2.8877DBD0]

We may need to get a few people to respond to this to find out an average…

**Comment by onaforeignshore** [comment]
I will stop pushing updates to this until @dritter has finished his merge and then I'll base this on that

**Comment by onaforeignshore** [comment]
Superceded by #875. Closing

**Pull request closed without merging**
