### PR TITLE
Made the code comply to shellcheck.net suggestions as much as possible

### PR DESCRIPTION
**Pull request by dritter**
.. There are still some suggestions unmatched, but these are mostly not possible. I managed to get from 116 comments to 25, which is pretty good. :)

### CODE REVIEW

**Comment by bhilburn** [comment]
@dritter - Looks like same thing happened with this one. Can you update this branch to make it a clean merge?

**Comment by dritter** [comment]
@bhilburn Done.

**Comment by bhilburn** [comment]
Looks like the merge of #90 hosed this one again, hah. Can you cleanup a second time?

**Comment by dritter** [comment]
@bhilburn cleaned up again. ;)

**Pull request merged**
