### PR TITLE
Strip the whitespace of OSX `wc` with pure zsh. No need to install `coreutils`.

### LINKED ISSUE #60: Question mark doesn't go away in git repository
Just updated to the latest version (c853be57e7efa79f9818394e3aec7900a6a35516) from a fairly old one, and now I can't seem to get rid of the question mark in the git `vcs` segment.

Here's a screenshot:
screen shot 2015-07-19 at 4 06 03 pm

### PR DESCRIPTION
**Pull request by dritter**
At first, I havn't installed `coreutils`. It took me a while to figure out that this was the necessary package to install to get this Theme running. Without `tr`, there is no need to install `coreutils`.

This is the second approach to fix #60 .

@natemccurdy Can you verify my fix? 
Thx. :)

### CODE REVIEW

**Comment by natemccurdy** [comment]
@dritter That fixed it! :+1:

**Comment by bhilburn** [comment]
@dritter - We don't need the white-space stripping in `function +vi-git-aheadbehind()`, too?

**Comment by dritter** [comment]
@bhilburn we strip the whitespace a line later.. But that one is just for optical reasons - no real functionality behind it. I put that line a while ago, when a colleague of mine complained about unwanted whitespace..

**Comment by natemccurdy** [comment]
@bhilburn The variables `$behind` and `$ahead` are stripped of whitespace [here](https://github.com/bhilburn/powerlevel9k/blob/7f83bac947893175ef937e26f1a3bc8a389d1718/powerlevel9k.zsh-theme#L354) and [here](https://github.com/bhilburn/powerlevel9k/blob/7f83bac947893175ef937e26f1a3bc8a389d1718/powerlevel9k.zsh-theme#L359) using ZSH's `${variable// /}` syntax

Also, the `(( ))` test ignores whitespace before a number, so that works as intended.

**Comment by bhilburn** [comment]
@dritter @natemccurdy - Ah, yes, I see, now. Thanks for pointing that out!

I'll test it out soon to confirm, and then merge. Thanks, guys!

**Comment by bhilburn** [comment]
Awesome! Thanks, @dritter and @natemccurdy!

**Pull request merged**
