### PR TITLE
status: show signal name

### PR DESCRIPTION
**Pull request by docwhat**
This makes signal exit status easy to understand.  Instead of just
showing exit code "137", you now see "KILL(-9)".

Based on #580 by @sei40kr (thanks!)

### CODE REVIEW

**Comment by docwhat** [comment]
I can add a flag if you want, but this is so sexy, I don't think it needs it. 😎

**Comment by bhilburn** [comment]
@docwhat - Fantastic!

I would like for this new mode to be the default, but I'd still like to have the old mode available for those that want it. Would you mind adding a flag to show the true error code, but defaulting it to `false`?

**Comment by docwhat** [comment]
Done, @bhilburn

**Comment by bhilburn** [comment]
Nicely implemented, @docwhat, and this is a really fantastic idea, @sei40kr! This is a really neat feature `=)`

**Pull request merged**
