### PR TITLE
battery icon set and color array

### PR DESCRIPTION
**Pull request by onaforeignshore**
This PR allows the user to set a battery icon set using a string or array for different levels, 

```
# POWERLEVEL9K_BATTERY_STAGES accepts either a string or an array.
# Note that if you use a string for characters that are wider than a single character will cause the icon to be very
# close to the remaining time. In this case, it is better to use the array version of `POWERLEVEL9K_BATTERY_STAGES`,
# so that you can add a space after.

# Uncomment only one of the following, or create your own

#POWERLEVEL9K_BATTERY_STAGES=""	#  \uF244  \uF243  \uF242  \uF241  \uF240
#POWERLEVEL9K_BATTERY_STAGES=("\uF244 " "\uF243 " "\uF242 " "\uF241 " "\uF240 ")

#POWERLEVEL9K_BATTERY_STAGES="▁▂▃▄▅▆▇█"
#POWERLEVEL9K_BATTERY_STAGES=("\u2581" "\u2582" "\u2583" "\u2584" "\u2585" "\u2586" "\u2587" "\u2588")

#POWERLEVEL9K_BATTERY_STAGES="▏▎▍▌▋▊▉█"
#POWERLEVEL9K_BATTERY_STAGES=("\u258F" "\u258E" "\u258D" "\u258C" "\u258B" "\u258A" "\u2589" "\u2588")

# Uncomment all 5 lines if you want to use this indicator
#POWERLEVEL9K_BATTERY_STAGES=(
#	"▏    ▏" "▎    ▏" "▍    ▏" "▌    ▏" "▋    ▏" "▊    ▏" "▉    ▏" "█    ▏"
#	"█▏   ▏" "█▎   ▏" "█▍   ▏" "█▌   ▏" "█▋   ▏" "█▊   ▏" "█▉   ▏" "██   ▏"
#	"██   ▏" "██▎  ▏" "██▍  ▏" "██▌  ▏" "██▋  ▏" "██▊  ▏" "██▉  ▏" "███  ▏"
#	"███  ▏" "███▎ ▏" "███▍ ▏" "███▌ ▏" "███▋ ▏" "███▊ ▏" "███▉ ▏" "████ ▏"
#	"████ ▏" "████▎▏" "████▍▏" "████▌▏" "████▋▏" "████▊▏" "████▉▏" "█████▏" )
```

It also allows the user to override the default color based on the current charge using a color array.

```
# *** choose from here for changing background by current battery level
# set if you want the background to change color with level. this overrides the state settings in the color selection.
# You can still specify foreground color and bold though.
#POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(196 202 208 214 220 226 190 154 118  82  46) # bright
#POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(124 130 136 142 148 112  76  40  34  28  22) # normal
#POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(  88  94 100 106  70  34  28  22) # subdued
```

*NOTE* This automatically calculates the icon and color changes based on the length of the array/string provided

### CODE REVIEW

**Comment by bhilburn** [comment]
@onaforeignshore - This is a really impressive PR.

Can you update the PR to add the documentation that you put in the PR description to the README? I'd like to make sure this is well documented for users =)

**Comment by onaforeignshore** [comment]
`README.md` updated, please check for clarity.

**Comment by bhilburn** [comment]
Merged!

This is really fantastic work, @onaforeignshore! Thanks for the great enhancement =)

**Comment by bhilburn** [comment]
It looks like I forgot to close this when I merged it. Oops!

**Pull request closed without merging**
