### PR TITLE
Improved color detection

### PR DESCRIPTION
**Pull request by dritter**
Added a new function `isSameColor` to handle color comparisons. It is now possible to compare ANSI colors (e.g. "black" or "bg-red") with ZSH-style colors (e.g. "001"). This way the subsegments work much better, as users can define color codes the way they like.

#### Example

`isSameColor bg-red red && echo true || echo false` -> returns true
`isSameColor bg-red 009 && echo true || echo false` -> returns true
`isSameColor 001 9 && echo true || echo false` -> returns true
`isSameColor red black && echo true || echo false` -> returns false

So, it doesn't matter if users define colors in numeric ZSH-style or ANSI-style.

### CODE REVIEW

**Comment by bhilburn** [comment]
@dritter - Great idea!!

What do you think about moving all of our utility functions out of `powerlevel9k.zsh-theme` and into a supplemental file that we then include in our theme file? With this change, we will have ~300 lines of utility functions that aren't strictly theme code, and I think re-organizing the code would make it easier to navigate.

Thoughts?

**Comment by dritter** [comment]
I already thought about moving this functions to an own project, as other projects could benefit from it. But with a package manager missing, I think it is better to have it - like you said - in separate files.

Maybe this is something we want for other parts as well? Thinking of the supplemental vcs-functions, or the icon definitions.. How about that?

**Comment by bhilburn** [comment]
@dritter - Yeah, I think we need to keep it in-house, but just split the files.

In terms of other things to break-out... you're right, breaking out the vcs functions might be good, as well. Same with the icons. Can you put together a changeset that breaks these items out?

**Comment by dritter** [comment]
@bhilburn Here we go. There are a bunch of new files now.

**Comment by bhilburn** [comment]
Awesome work, @dritter!!

This is a really significant change, so I want to be sure everything is all set before I merge. I am going to pull this and use it myself for a few days before merging.

**Comment by dritter** [comment]
:+1: That sounds like a good plan. ;) Hopefully it works out of the box.

**Comment by bhilburn** [comment]
@dritter - It's totally broken for me =(

When I open a terminal with your branch checked-out, I get this:

```
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:source:24: no such file or directory: /home/bhilburn/.oh-my-zsh/custom/themes/functions/icons.zsh
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:source:30: no such file or directory: /home/bhilburn/.oh-my-zsh/custom/themes/functions/utilities.zsh
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:source:36: no such file or directory: /home/bhilburn/.oh-my-zsh/custom/themes/functions/colors.zsh
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:source:42: no such file or directory: /home/bhilburn/.oh-my-zsh/custom/themes/functions/vcs.zsh
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:58: command not found: set_default
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:59: command not found: set_default
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:86: command not found: set_default
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:141: command not found: set_default
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:483: command not found: set_default
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:620: command not found: set_default
zsh: set_default: command not found...
/home/bhilburn/.oh-my-zsh/custom/themes/powerlevel9k.zsh-theme:621: command not found: set_default
zsh: defined: command not found...                                                                                                
build_left_prompt:1: command not found: defined
zsh: print_icon: command not found...
prompt_dir:18: command not found: print_icon
zsh: isSameColor: command not found...
left_prompt_segment:17: command not found: isSameColor
zsh: print_icon: command not found...
prompt_vcs:19: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:20: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:24: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:25: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:31: command not found: print_icon
zsh: print_icon: command not found...
left_prompt_end:2: command not found: print_icon
zsh: defined: command not found...
build_right_prompt:1: command not found: defined
zsh: isSameColor: command not found...
right_prompt_segment:15: command not found: isSameColor
zsh: print_icon: command not found...
right_prompt_segment:24: command not found: print_icon
zsh: isSameColor: command not found...
right_prompt_segment:15: command not found: isSameColor
zsh: print_icon: command not found...
right_prompt_segment:24: command not found: print_icon
~ zsh: defined: command not found...                                                                                 212015:34:11
build_left_prompt:1: command not found: defined
zsh: print_icon: command not found...
prompt_dir:18: command not found: print_icon
zsh: isSameColor: command not found...
left_prompt_segment:17: command not found: isSameColor
zsh: print_icon: command not found...
prompt_vcs:19: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:20: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:24: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:25: command not found: print_icon
zsh: print_icon: command not found...
prompt_vcs:31: command not found: print_icon
zsh: print_icon: command not found...
left_prompt_end:2: command not found: print_icon
zsh: defined: command not found...
build_right_prompt:1: command not found: defined
zsh: isSameColor: command not found...
right_prompt_segment:15: command not found: isSameColor
zsh: print_icon: command not found...
right_prompt_segment:24: command not found: print_icon
zsh: isSameColor: command not found...
right_prompt_segment:15: command not found: isSameColor
zsh: print_icon: command not found...
right_prompt_segment:24: command not found: print_icon
~                                                                                                                                                                                                                                                 212015:34:17
```

**Comment by dritter** [comment]
Nooo. :cry: 

Can't believe `dirname "$0"` behaves so differently on Mac and Linux.. I'll work on that.

**Comment by dritter** [comment]
@bhilburn Wait. Do you link the theme to `.oh-my-zsh/custom/themes/`?
To get the correct path to the other scripts (to `source` them), we have to get the current directory of the Theme. For that purpose I use `dirname "$0"`. That command usually returns "." (current directory). In a link-scenario there is no subfolder "functions".

Can you try to use the "checkout-method" and reference the `ZSH_THEME="powerlevel9k/powerlevel9k"`?

**Comment by bhilburn** [comment]
@dritter - Yup, that's it. All I needed to do was to symlink the entire directory instead of just the theme. Nice debugging!

Will proceed with testing =)

**Comment by dritter** [comment]
@bhilburn I just added some little code that dereferences links if necessary. Now it should work if the theme is linked.. :)

**Comment by dritter** [comment]
I just fixed a problem with prezto. There the theme gets set with the help of `zstyle`, which calles the theme as a function, and we have no chance to find the location of the theme file itself to source the other scripts. For that case I hardcoded the path to the theme file inside prezto. This is quite ugly and I would love to get rid of that. Unfortunately the only option I see is to convert our scripts to proper ZSH autoload-files, add them to `fpath` (<- here we need to get the proper location as well, which has the same problem), and autoload them from the theme. 
I think ZSH wasn't designed for that case. The user should usually decide which functions he wants to autoload and the theme should just make the output pretty..

Fair enough the current solution works as long as nobody tries to customize the path for prezto. But I think we should wait until that happens..

**Comment by bhilburn** [comment]
After testing this for a while, it looks solid. Merging.

Great contribution, @dritter!

**Pull request merged**
