### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by onaforeignshore**
# Project Documentation / File Commenting

## Synopsis

I was thinking about the documenting part of this project, and thought it might be useful to have a reference of all the functions and their calls on the project wiki for our and others' reference.

I searched online for any converters that would convert bash comments into GitHub markdown, and only found one - [shdoc](https://github.com/reconquest/shdoc). In my opinion, it is lacking a lot, even with the PR that is on the project. So, I have spent the last 3 days rewriting it from scratch.

I have named my version [sh2md](https://github.com/onaforeignshore/sh2md). Can you guys please take a look at it, and give me comments, as I think it would be useful to start commenting the files and functions in this way. As I have written the converter myself, it will be easy to add / change as required for the project.

I have included two files in this PR that have been commented in this way - `powerlevel9k.zsh-theme` and `functions/colors.zsh`. I have attached the output to the bottom of this post for you to preview as well.

## Requirements

The converter uses Gnu AWK. As this is available on most systems (and can be installed on Mac using Homebrew), I think it would be available to the majority of the contributors to use to create documentation for their files.

## TODO
- [ ] discuss the requirements for `powerlevel9k`
- [ ] discuss the styles and tags we would like to use
- [x] add a function to convert multiple line comments into paragraphs
- [ ] add more section tags as required

### File level comment block

```sh
################################################################
# @title powerlevel9k Theme
# @source https://github.com/bhilburn/powerlevel9k
#
# @authors
#   Ben Hilburn
#   Dominic Ritter
#
# @info
# This theme was inspired by [agnoster's Theme](https://gist.github.com/3712874)
#
# For basic documentation, please refer to the README.md in the top-level
# directory. For more detailed documentation, refer to the
# [project wiki](https://github.com/bhilburn/powerlevel9k/wiki), hosted
# on Github.
#
# There are a lot of easy ways you can customize your prompt segments and
# theming with simple variables defined in your `~/.zshrc`.
################################################################
```

---

# powerlevel9k Theme

### Source(s)

[https://github.com/bhilburn/powerlevel9k](#https://github.com/bhilburn/powerlevel9k)

### Author(s)

- Ben Hilburn
- Dominic Ritter

### File Description

_This theme was inspired by [agnoster's Theme](https://gist.github.com/3712874)_

_For basic documentation, please refer to the README.md in the top-level directory. For more detailed documentation, refer to the [project wiki](https://github.com/bhilburn/powerlevel9k/wiki), hosted on Github._

_There are a lot of easy ways you can customize your prompt segments and theming with simple variables defined in your `~/.zshrc`._

---

### Function comment blocks

```sh
#!/usr/bin/env zsh
# vim:ft=zsh ts=2 sw=2 sts=2 et fenc=utf-8
################################################################
# @title Color functions
# @source https://github.com/bhilburn/powerlevel9k
# @info
# This file holds some color-functions for the powerlevel9k-ZSH-theme
##

################################################################
# @description
# Get numerical color codes. That way we translate ANSI codes ZSH-Style color codes.
#
# @example
#   getColorCode 'black'
#
# @args
#   $1 string|number If string, ANSI color code.
#
# @returns
#   Zsh style color code.
##
function getColorCode() {
  # ...
}

################################################################
# @description
# Check if two colors are equal, even if one is specified as ANSI code.
#
# @examples isSameColor 'black' 0
#   isSameColor 'white' 0
#
# @args
#   $1 string|number First color.
#   $2 string|number Second color.
#
# @returns
#   true if they are the same color.
#   false if they are different colors.
#
# @see
#   getColorCode
##
function isSameColor() {
  # ...
}
```

---

# Color functions

### Source(s)

[https://github.com/bhilburn/powerlevel9k](#https://github.com/bhilburn/powerlevel9k)

### File Description

_This file holds some color-functions for the powerlevel9k-ZSH-theme_

## Table of Contents

- [getColorCode()](#getColorCode)
- [isSameColor()](#isSameColor)

## getColorCode()

Get numerical color codes. That way we translate ANSI codes ZSH-Style color codes.

### Example

```sh
getColorCode 'black'
```

### Arguments

- **$1** (string|number) If string, ANSI color code.

### Returns

- Zsh style color code.

## isSameColor()

Check if two colors are equal, even if one is specified as ANSI code.

### Example

```sh
isSameColor 'black' 0
isSameColor 'white' 0
```

### Arguments

- **$1** (string|number) First color.
- **$2** (string|number) Second color.

### Returns

- true if they are the same color.
- false if they are different colors.

### See also

- [getColorCode](#getColorCode)

---

### CODE REVIEW

**Comment by onaforeignshore** [comment]
I changed the name of the project to sh2md as there are already a few projects name shelldoc. Ignore the conflicts, as this is about the documentation, not the files.

**Comment by bhilburn** [comment]
@onaforeignshore - Great idea! More documentation would be excellent, and auto-generating it from the code comments, a la Doxygen, is a great way to build out developer documentation.

It's really hard to see what you've done, though, because this PR is built on top of @dritter's `async` work, so looking at the diff not only shows your changes but all of the changes @dritter has made over the course of months of development. It also means that it will be impossible to merge this PR until @dritter's work is done, which is obviously not ideal :)

What would be best is if you could rebase this branch onto `next`. It looks like there are four commits that are part of this work:

commits

Assuming these commits are in some branch, call it `docs`, you can rebase it onto `next` by doing:

```
$ git checkout docs
$ git rebase next
```

If these commits are not in their own branch, then we can move them over to one by cherry-picking. Let me know if you need help, here!

**Comment by onaforeignshore** [comment]
I couldn't rebase, so I created a branch off next called docs

**Comment by onaforeignshore** [comment]
Closed due to PR against Next

**Pull request closed without merging**
