### PR TITLE
OS Icon-prompt

### PR DESCRIPTION
**Pull request by dritter**
Added an icon that gives a little hint about the current operating system. It may sound stupid, but nowadays it is quite easy to work on different OSes in parallel (e.g. with a VM or via SSH).

### CODE REVIEW

**Comment by bhilburn** [comment]
Hey @dritter - I love this idea! Great work.

I've checked out the code and tested it , and have a few questions before calling it final:

1. What font do you have that provides the Linux icon? I'm using Powerline Deja Vu, and I don't have that Unicode character. How common is it?
2. Right now, the OS detection is done once (I think?), but we then go through the conditional string parsing to set the appropriate icon with every single prompt draw. Since the OS will never change out from under us, why not just set the icon once rather than parsing strings for each prompt draw? Thoughts?

**Comment by dritter** [comment]
@bhilburn Good questions. :)

1. I am using `Droid Sans Mono Awesome`. The Icons should be quite common, as (except for the apple-icon) they are in the public unicode space:
[Penguin-Icon](http://unicode-search.net/unicode-namesearch.pl?term=1F427&.submit=Search)
[Sun-Icon](http://unicode-search.net/unicode-namesearch.pl?term=1F31E&.submit=Search)
[Beastie-Icon](http://unicode-search.net/unicode-namesearch.pl?term=1F608&.submit=Search)
[Apple-Icon](http://unicode-search.net/unicode-namesearch.pl?term=F8FF&.submit=Search), which is in private space, but should work on every OSX.

    Interestingly, as I retested it, I had some Issues with `echo $'\u1F427'`.. Instead echoing the character directly worked as expected: `echo 🐧`.

2. Yep, only once. Indeed, it may be better to figure out the right icon when the OS is detected. I just wanted to keep that together. But now I moved it..

**Comment by dritter** [comment]
@bhilburn I found it! It seems there is a big difference whether you print unicode with an uppercase `\U`, or a lowercase `\u`. I always thought that doesn't matter, but it does. In my last commit, I changed all appearances from lowercase to uppercase..

**Comment by bhilburn** [comment]
Hm, yeah, those characters don't exist in my system font. They don't even render on the referenced websites you gave, actually.

Also, `echo $'\u1F427' $'\U1F427'` shows gibberish for both: `ὂ7 🐧`

I think these glyphs are only in the `Awesome` version of Powerline fonts. 

Here's my suggestion: Let's treat these like we do for all of the other symbols. If someone has the 'awesome' fonts turned on, then great, let's use these glyphs. For non-awesome fonts, let's provide a fall-back symbol / character / string so that this segment can still be used.

Thoughts?

**Comment by dritter** [comment]
Excellent idea! I've just done it so!

The difference between `\u` and `\U` still bothers me, but I think the uppercase one seems more stable. Could you double check that?

**Comment by bhilburn** [comment]
Hey! I made some changes and pushed them to to a branch [dritter-os-icon](https://github.com/bhilburn/powerlevel9k/tree/dritter-os-icon).

The code was still evaluating a case statement to set an OS icon with every call to the prompt segment function for `os_icon`. I moved that statement out, combined it with the OS detection case statement, and stuck it at the top of the file. My goal is to evaluate as little as possible with each prompt draw to keep things fast `=)`

Two other minor changes:

1. You had OS detection for 'Dragonfly' and 'OpenBSD', but no icon for those OSes, so I removed them.
2. I changed the foreground color to something a bit brighter - on my screen, the previous color blended into the BG a bit too much.

Pull my branch, give it a shot, and let me know what your thoughts are!

**Comment by dritter** [comment]
@bhilburn looks awesome!

1. For Completeness, I added them again. They are a part of the BSD family so the BSD icon should be fine..

2. Nice. looks good. :)

**Comment by bhilburn** [comment]
Okay, so I was just doing some final testing on this branch before a merge, and I found an issue. In certain scenarios that I haven't quite figured out yet, I get a garbage UTF character in my VCS segment. But it doesn't always show up... example:

utf

It has to be a result of the change from `\u` to `\U`. Any thoughts, @dritter?

**Comment by bhilburn** [comment]
Okay, update on my above post. Even when not using this branch, I'm now seeing garbage characters.

I just upgraded from Fedora20 to Fedora22, and I suspect something is hosed. Working on sorting it out, now.

**Comment by dritter** [comment]
@bhilburn You could check my `character_protection`-Branch (see #56 ) even that this branch needs an update, there might be a fix for your problem..

**Comment by dritter** [comment]
@bhilburn I think the biggest suspect is the uppercase `\U`. Could you change that back to `\u` and see if the error persists? `sed -i "s/\\\U/\\\u/g" powerlevel9k.zsh-theme`

**Comment by bhilburn** [comment]
This work has been merged into `next` for testing.

https://github.com/bhilburn/powerlevel9k/tree/next

**Pull request closed without merging**
