### PR TITLE
Improves ram prompt #415

### PR DESCRIPTION
**Pull request by Darkheir**
For now here are the changes:

* For OS X display the sum of Pages free and Pages inactive. See https://support.apple.com/en-us/HT201538
* For Non BSD use MemAvailable instead of MemFree. See http://www.linuxatemyram.com/

For now no satisfying solution has been found for BSD systems

### CODE REVIEW

**Comment by Darkheir** [comment]
Linked to issue #415

**Comment by dritter** [comment]
Hey @Darkheir !

Thanks for your contribution. I hadn't had time to look into your changes. Btw. I am preparing a FreeBSD-VM so we can have a look at the ram segment under this OS.

**Comment by bhilburn** [comment]
Awesome work, @Darkheir! I'm eager to get this merged.

I've merged @dritter's new FreeBSD VM into `next`, so if you rebase onto the latest `next` you should be able to test pretty easily with the Vagrant VM. Would you mind giving it a go?

**Comment by Darkheir** [comment]
Ok, I will try to find some time this week-end !

**Comment by bhilburn** [comment]
Awesome, @Darkheir! Keep us posted :)

**Comment by Darkheir** [comment]
I find a way to get available ram on BSD. Please review it and see if it is OK for you.

**Comment by dritter** [comment]
@rjorgenson Could you confirm that works with your BSD machine? I would test it with the same VM that @Darkheir used to develop that feature..

**Comment by rjorgenson** [comment]
@dritter Yes that does work for me =]

**Comment by dritter** [comment]
Awesome! Thanks for testing! :)

**Comment by bhilburn** [comment]
Excellent work, @Darkheir! This has been merged into next.

Thanks for the contribution, @Darkheir, and thanks to @rjorgenson and @dritter for their testing and feedback!

**Pull request merged**
