### PR TITLE
Fix for #575 - RVM segment version reporting

### PR DESCRIPTION
**Pull request by rjorgenson**
This is the solution I was able to come up with =]

### CODE REVIEW

**Comment by docwhat** [comment]
Competing change: #583 

**FIGHT!**

:smiley:

**Comment by docwhat** [comment]
@rjorgenson: 

You should:

- change the destination branch to `bhilburn:next` (click "EDIT" next to the subject and you can change it there).
- Do a `git rebase origin/next` to get rid of the ugly merge commits.

**Comment by rjorgenson** [comment]
@docwhat he requested we submit PR against master as a bugfix

**Comment by rjorgenson** [comment]
the rebasing doesn't seem to be doing anything but adding commits =/

**Comment by rjorgenson** [comment]
closing out in favor of better solution in #582 =]

**Pull request closed without merging**
