### PR TITLE
[Docs] Fixes typo in README

### PR DESCRIPTION
**Pull request by Syphdias**
- fixes missing backtick
- corrects wrong variable name and adds backticks around it

### CODE REVIEW

**Comment by Syphdias** [comment]
OK, not quite sure how the Travis checks fail here...

**Comment by bhilburn** [comment]
@Syphdias - Per our conversation in Gitter, I restarted the Travis build for this PR, and the tests are still failing. I'm honestly not sure what to make of that, especially since the latest tests for `next` are passing (see [here](https://travis-ci.org/bhilburn/powerlevel9k/builds/432405877)), and this PR now has no changes relative to its target merge on `next`. WAT.

I cannot imagine this is an issue with your PR, @Syphdias.

@dritter - I know you are in the middle of moving right now, but whenever you get a chance could you peek at Travis? I'm very confused, hah.

**Comment by Syphdias** [comment]
> [...] and this PR now has no changes relative to its target merge on `next`. WAT.

Yeah, I reverted my changes to verify my changes were not the reason the test failed. I'll re-revert or reset it to get the changes into this PR again.

**Comment by dritter** [comment]
I fixed the tests on `next`. It looks like travis changed its infrastructure. We needed to unset `SSH_CLIENT` and `SSH_TTY` to get the tests running again.

**Comment by Syphdias** [comment]
I think I'm done now :)

**Comment by dritter** [comment]
Thx @Syphdias

**Pull request merged**
